ci/cd

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -42,32 +42,32 @@ jobs:
       - name: Push Docker image
         run: docker push ${{ secrets.DOCKER_USER }}/project_mini:terbaru
 
-  deploy:
-    # needs: build-and-push-docker
-    runs-on: ubuntu-latest
-    env:
-        IMAGE_URI: '${{ secrets.DOCKER_USER }}/project_mini:terbaru'
-        EC2_HOST: ${{ secrets.EC2_HOST }}
-        EC2_USER: ${{ secrets.EC2_USER }}
-    steps:
-    - name: Check out the code
-      uses: actions/checkout@v2
-    - name: Create PEM file from secret
-      run: |
-        echo "${{ secrets.EC2_PEM }}" > ec2-key.pem
-        chmod 600 ec2-key.pem  # Set appropriate permissions
+  # deploy:
+  #   # needs: build-and-push-docker
+  #   runs-on: ubuntu-latest
+  #   env:
+  #       IMAGE_URI: '${{ secrets.DOCKER_USER }}/project_mini:terbaru'
+  #       EC2_HOST: ${{ secrets.EC2_HOST }}
+  #       EC2_USER: ${{ secrets.EC2_USER }}
+  #   steps:
+  #   - name: Check out the code
+  #     uses: actions/checkout@v2
+  #   - name: Create PEM file from secret
+  #     run: |
+  #       echo "${{ secrets.EC2_PEM }}" > ec2-key.pem
+  #       chmod 600 ec2-key.pem  # Set appropriate permissions
 
-    - name: Deploy to EC2
-      run: |
+  #   - name: Deploy to EC2
+  #     run: |
 
-        ssh -i ec2-key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
+  #       ssh -i ec2-key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
 
-          sudo docker ps -q --filter "name=my-container" | grep -q . && docker stop my-container || true
-          sudo docker rm my-container || true
+  #         sudo docker ps -q --filter "name=my-container" | grep -q . && docker stop my-container || true
+  #         sudo docker rm my-container || true
 
-          sudo docker pull $IMAGE_URI
+  #         sudo docker pull $IMAGE_URI
 
-          sudo docker run -d --name my-container -p 8000:8000 $IMAGE_URI
-        EOF
-    - name: Clean up PEM file
-      run: rm -f ec2-key.pem
+  #         sudo docker run -d --name my-container -p 8000:8000 $IMAGE_URI
+  #       EOF
+  #   - name: Clean up PEM file
+  #     run: rm -f ec2-key.pem
