project deployment

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,72 +1,89 @@
-name: deployment
+name: Deployment Workflow
 
 on:
-    push:
-        branches:
-            - master
+  push:
+    branches:
+      - master
 
 jobs:
-    test:
-        runs-on: ubuntu-latest
-        steps:
-            - name: checkout the code
-              uses: actions/checkout@v2
-            - name: setup go
-              uses: actions/setup-go@v3
-              with:
-                go-version: '1.21'
-            - name: run test
-              run: |
-                go test -v ./...
+  test:
+    runs-on: ubuntu-latest
+    steps:
+      # Checkout the code
+      - name: Checkout the code
+        uses: actions/checkout@v2
 
-    build-and-push-docker:
-        runs-on: ubuntu-latest
-        needs: test
-        steps:
-            - name: checkout the code
-              uses: actions/checkout@v2
-            - name: create env file
-              run: |
-                echo "${{secrets.ENV}}" >> .env
-            - name: build docker
-              run: docker build -t fajarsdq/go-carbon-tracker:1.0.0 .
-            - name: docker hub login
-              uses: docker/login-action@v1
-              with: 
-                username: ${{secrets.DOCKER_USER}}
-                password: ${{secrets.DOCKER_TOKEN}}
-            - name: push image
-              run: docker push fajarsdq/go-carbon-tracker:1.0.0
-    deploy:
-      needs: build-and-push-docker
-      runs-on: ubuntu-latest
-      env:
-        IMAGE_URI: 'fajarsdq/go-carbon-tracker:1.0.0'
-        EC2_HOST: ${{ secrets.EC2_HOST }}
-        EC2_USER: ${{ secrets.EC2_USER }}
+      # Setup Go environment
+      - name: Setup Go
+        uses: actions/setup-go@v2
+        with:
+          go-version: '1.21'
 
-      steps:
-        - name: Check out the code
-          uses: actions/checkout@v2
+      # Run tests
+      - name: Run Tests
+        run: go test -v ./...
 
-        - name: Create PEM file from secret
-          run: |
-            echo "${{ secrets.EC2_PEM }}" > ec2-key.pem
-            chmod 600 ec2-key.pem  # Set appropriate permissions
+  build-and-push-docker:
+    runs-on: ubuntu-latest
+    needs: test
+    steps:
+      # Checkout the code
+      - name: Checkout the code
+        uses: actions/checkout@v2
 
-        - name: Deploy to EC2
-          run: |
-            ssh -i ec2-key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
-              # Stop the current container if running
-              sudo docker ps -q --filter "name=carbon-tracker" | grep -q . && sudo docker stop carbon-tracker || true
-              sudo docker rm carbon-tracker || true
+      # Create .env file from secret
+      - name: Create .env file
+        run: echo "${{ secrets.ENV }}" > .env
 
-              # Pull the latest image from ECR
-              sudo docker pull $IMAGE_URI
+      # Login to Docker Hub
+      - name: Docker Hub Login
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_USER }}
+          password: ${{ secrets.DOCKER_TOKEN }}
 
-              # Run the new container
-              sudo docker run -d --name carbon-tracker -p 1323:1323 $IMAGE_URI
-            EOF
+      # Build Docker image
+      - name: Build Docker Image
+        run: docker build -t ${{ secrets.DOCKER_USER }}/mini_golang_airquality:latest .
 
-        - name: Clean up PEM file
-          run: rm -f ec2-key.pem
+      # Push Docker image to Docker Hub
+      - name: Push Docker Image
+        run: docker push ${{ secrets.DOCKER_USER }}/mini_golang_airquality:latest
+
+  deploy-to-ec2:
+    needs: build-and-push-docker
+    runs-on: ubuntu-latest
+    env:
+      IMAGE_URI: '${{ secrets.DOCKER_USER }}/mini_golang_airquality:latest'
+      EC2_HOST: ${{ secrets.EC2_HOST }}
+      EC2_USER: ${{ secrets.EC2_USER }}
+
+    steps:
+      # Checkout the code
+      - name: Checkout the Code
+        uses: actions/checkout@v2
+
+      # Create PEM file from secret
+      - name: Create PEM File
+        run: |
+          echo "${{ secrets.EC2_PEM }}" > ec2-key.pem
+          chmod 600 ec2-key.pem
+
+      # Deploy to EC2
+      - name: Deploy to EC2
+        run: |
+          ssh -i ec2-key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
+            # Stop the current container if running
+            sudo docker ps -q --filter "name=mini_golang_airquality" | grep -q . && sudo docker stop mini_golang_airquality || true
+            sudo docker rm mini_golang_airquality || true
+
+            # Pull the latest image from Docker Hub
+            sudo docker pull $IMAGE_URI
+
+            # Run the new container
+            sudo docker run -d --name mini_golang_airquality -p 8080:8080 $IMAGE_URI
+          EOF
+
+      # Clean up PEM file
+      - name: Clean up PEM File
+        run: rm -f ec2-key.pem
